#!/usr/bin/env python3
"""Regenerate INDEX.md from the frontmatter of every page under wiki/.

The index is a generated file: never hand-merge it. On a conflict, take either
side to end the conflict state, then run this again. Output is fully sorted so
that two agents regenerating the same tree produce byte-identical results.

Usage:
    python tools/build-index.py              # rewrite INDEX.md
    python tools/build-index.py --check      # report problems, write nothing
    python tools/build-index.py --root PATH  # operate on a hub elsewhere

Exit codes:
    0  ok
    1  --check found pages with missing required fields
    2  bad invocation
"""

from __future__ import annotations

import argparse
import os
import sys

REQUIRED = ("type", "updated", "summary")
WIKI_DIR = "wiki"
INDEX_FILE = "INDEX.md"
BANNER = "<!-- generated by tools/build-index.py — do not edit by hand -->"


def parse_frontmatter(text: str) -> dict:
    """Minimal YAML-frontmatter reader: flat `key: value` pairs only.

    Deliberately dependency-free — a hub should not need pip install to
    regenerate its own index. Anything nested is ignored rather than guessed at.
    """
    if not text.startswith("---"):
        return {}
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    out: dict = {}
    for line in lines[1:]:
        stripped = line.strip()
        if stripped == "---":
            break
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        out[key] = value
    return out


def cell(value: str) -> str:
    """Escape a value for use inside a markdown table cell."""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def collect(root: str) -> tuple[list[dict], list[tuple[str, list[str]]]]:
    wiki = os.path.join(root, WIKI_DIR)
    if not os.path.isdir(wiki):
        sys.stderr.write("error: %s not found — run this from the hub root\n" % wiki)
        raise SystemExit(2)

    pages: list[dict] = []
    problems: list[tuple[str, list[str]]] = []

    for dirpath, dirnames, filenames in os.walk(wiki):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for name in sorted(filenames):
            if not name.endswith(".md"):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            with open(full, encoding="utf-8") as fh:
                meta = parse_frontmatter(fh.read())

            missing = [k for k in REQUIRED if not meta.get(k)]
            if missing:
                problems.append((rel, missing))

            group = os.path.relpath(dirpath, wiki).replace(os.sep, "/")
            pages.append(
                {
                    "path": rel,
                    "group": "(root)" if group == "." else group,
                    "type": meta.get("type", ""),
                    "status": meta.get("status", ""),
                    "updated": meta.get("updated", ""),
                    "summary": meta.get("summary", ""),
                }
            )

    pages.sort(key=lambda p: (p["group"], p["path"]))
    problems.sort()
    return pages, problems


def render(pages: list[dict]) -> str:
    blocks: list[str] = [BANNER, "", "# Index", "", "%d pages." % len(pages)]

    current = None
    rows: list[str] = []

    def flush() -> None:
        if current is not None:
            blocks.append("")
            blocks.append("## %s" % current)
            blocks.append("")
            blocks.append("| path | type | updated | summary |")
            blocks.append("| --- | --- | --- | --- |")
            blocks.extend(rows)

    for page in pages:
        if page["group"] != current:
            flush()
            current = page["group"]
            rows = []
        rows.append(
            "| `%s` | %s | %s | %s |"
            % (page["path"], cell(page["type"]), cell(page["updated"]), cell(page["summary"]))
        )
    flush()

    return "\n".join(blocks).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="hub root (default: current directory)")
    ap.add_argument("--check", action="store_true", help="report problems, write nothing")
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    pages, problems = collect(root)

    for rel, missing in problems:
        sys.stderr.write("missing %s: %s\n" % (",".join(missing), rel))

    if args.check:
        if problems:
            sys.stderr.write("\n%d page(s) missing required frontmatter.\n" % len(problems))
            return 1
        sys.stderr.write("ok: %d pages, all required fields present.\n" % len(pages))
        return 0

    target = os.path.join(root, INDEX_FILE)
    new = render(pages)
    old = None
    if os.path.exists(target):
        with open(target, encoding="utf-8") as fh:
            old = fh.read()
    if old == new:
        sys.stderr.write("unchanged: %s (%d pages)\n" % (INDEX_FILE, len(pages)))
        return 0
    # newline="" keeps the LF endings the .gitattributes rule expects
    with open(target, "w", encoding="utf-8", newline="") as fh:
        fh.write(new)
    sys.stderr.write("wrote %s (%d pages)\n" % (INDEX_FILE, len(pages)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
